# Generated by Django 4.2.7 on 2023-11-23 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('invoice_no', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('date_due', models.DateField()),
                ('bill_memo', models.TextField()),
                ('paid_in_full', models.BooleanField(default=False)),
                ('Reference', models.CharField(max_length=255)),
                ('Sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('external_account_no', models.CharField(max_length=255)),
                ('default_category', models.BooleanField(default=False)),
                ('system_category', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.category')),
                ('vendortypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.vendortype')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('bankaccount_id', models.IntegerField()),
                ('check_no', models.CharField(max_length=255)),
                ('check_cut_date', models.DateField()),
                ('check_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('print_date', models.DateField()),
                ('check_memo', models.TextField()),
                ('Reference', models.CharField(max_length=255)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='categorytype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.categorytype'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_account_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.category'),
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('memo', models.TextField()),
                ('vendor_credit_id', models.IntegerField()),
                ('Reference', models.CharField(max_length=255)),
                ('bills_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.category')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.vendors'),
        ),
    ]
